### ISSUE TITLE
Various design problems with BitWeapon

### ISSUE THREAD

**Issue by feature** [Perotins/BitBattle#3]
### Problems
1. Constructing a `BitWeapon` is too complicated, due to the amount of parameters.
2. Functionality of ranged and melee weapons is combined together in a single class.
3. Weapons builds are contained inside the `BitWeapon`, and represented as a `Map<String, String>`
4. Fields that should be immutable are mutable. (i.e `name`)

**Comment by maximus-f** [comment]
1. Will change BitWeapon to an interface so we can implement instances of classes designed for either Projectiles or Melees

2. Applies to #1 

3. Strings are used for parsing to files on loading / saving, easier to transmit than an object. This is just for the items used, as projectiles will have a base item and then another item as the projectile itself. This will only apply to projectiles, melees will just have one item representing them.

4. Will make immutable
